// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/proto/control_plane.proto

package controlplane

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecuteSandboxRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TaskId         string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Payload        []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	JurisdictionId string                 `protobuf:"bytes,3,opt,name=jurisdiction_id,json=jurisdictionId,proto3" json:"jurisdiction_id,omitempty"`
	Location       *GPSCoordinates        `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecuteSandboxRequest) Reset() {
	*x = ExecuteSandboxRequest{}
	mi := &file_api_proto_control_plane_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteSandboxRequest) ProtoMessage() {}

func (x *ExecuteSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_plane_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteSandboxRequest.ProtoReflect.Descriptor instead.
func (*ExecuteSandboxRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_control_plane_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteSandboxRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ExecuteSandboxRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ExecuteSandboxRequest) GetJurisdictionId() string {
	if x != nil {
		return x.JurisdictionId
	}
	return ""
}

func (x *ExecuteSandboxRequest) GetLocation() *GPSCoordinates {
	if x != nil {
		return x.Location
	}
	return nil
}

type ExecuteSandboxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Output        []byte                 `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteSandboxResponse) Reset() {
	*x = ExecuteSandboxResponse{}
	mi := &file_api_proto_control_plane_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteSandboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteSandboxResponse) ProtoMessage() {}

func (x *ExecuteSandboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_plane_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteSandboxResponse.ProtoReflect.Descriptor instead.
func (*ExecuteSandboxResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_control_plane_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteSandboxResponse) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *ExecuteSandboxResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ExecuteSandboxResponse) GetOutput() []byte {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *ExecuteSandboxResponse) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

type GPSCoordinates struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Altitude      float64                `protobuf:"fixed64,3,opt,name=altitude,proto3" json:"altitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GPSCoordinates) Reset() {
	*x = GPSCoordinates{}
	mi := &file_api_proto_control_plane_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GPSCoordinates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPSCoordinates) ProtoMessage() {}

func (x *GPSCoordinates) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_plane_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPSCoordinates.ProtoReflect.Descriptor instead.
func (*GPSCoordinates) Descriptor() ([]byte, []int) {
	return file_api_proto_control_plane_proto_rawDescGZIP(), []int{2}
}

func (x *GPSCoordinates) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *GPSCoordinates) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *GPSCoordinates) GetAltitude() float64 {
	if x != nil {
		return x.Altitude
	}
	return 0
}

type ManageSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"` // e.g., "START", "STOP", "UPDATE_JURISDICTION"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManageSessionRequest) Reset() {
	*x = ManageSessionRequest{}
	mi := &file_api_proto_control_plane_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManageSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManageSessionRequest) ProtoMessage() {}

func (x *ManageSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_plane_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManageSessionRequest.ProtoReflect.Descriptor instead.
func (*ManageSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_control_plane_proto_rawDescGZIP(), []int{3}
}

func (x *ManageSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ManageSessionRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type ManageSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManageSessionResponse) Reset() {
	*x = ManageSessionResponse{}
	mi := &file_api_proto_control_plane_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManageSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManageSessionResponse) ProtoMessage() {}

func (x *ManageSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_plane_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManageSessionResponse.ProtoReflect.Descriptor instead.
func (*ManageSessionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_control_plane_proto_rawDescGZIP(), []int{4}
}

func (x *ManageSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ManageSessionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type LogEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventType     string                 `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	EventData     []byte                 `protobuf:"bytes,2,opt,name=event_data,json=eventData,proto3" json:"event_data,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEventRequest) Reset() {
	*x = LogEventRequest{}
	mi := &file_api_proto_control_plane_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEventRequest) ProtoMessage() {}

func (x *LogEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_plane_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEventRequest.ProtoReflect.Descriptor instead.
func (*LogEventRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_control_plane_proto_rawDescGZIP(), []int{5}
}

func (x *LogEventRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *LogEventRequest) GetEventData() []byte {
	if x != nil {
		return x.EventData
	}
	return nil
}

func (x *LogEventRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type LogEventResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	LedgerHash     string                 `protobuf:"bytes,1,opt,name=ledger_hash,json=ledgerHash,proto3" json:"ledger_hash,omitempty"`
	SequenceNumber int64                  `protobuf:"varint,2,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LogEventResponse) Reset() {
	*x = LogEventResponse{}
	mi := &file_api_proto_control_plane_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEventResponse) ProtoMessage() {}

func (x *LogEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_plane_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEventResponse.ProtoReflect.Descriptor instead.
func (*LogEventResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_control_plane_proto_rawDescGZIP(), []int{6}
}

func (x *LogEventResponse) GetLedgerHash() string {
	if x != nil {
		return x.LedgerHash
	}
	return ""
}

func (x *LogEventResponse) GetSequenceNumber() int64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

var File_api_proto_control_plane_proto protoreflect.FileDescriptor

const file_api_proto_control_plane_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/proto/control_plane.proto\x12\fcontrolplane\x1a\x1fgoogle/protobuf/timestamp.proto\"\xad\x01\n" +
	"\x15ExecuteSandboxRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12'\n" +
	"\x0fjurisdiction_id\x18\x03 \x01(\tR\x0ejurisdictionId\x128\n" +
	"\blocation\x18\x04 \x01(\v2\x1c.controlplane.GPSCoordinatesR\blocation\"\xaa\x01\n" +
	"\x16ExecuteSandboxResponse\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x16\n" +
	"\x06output\x18\x03 \x01(\fR\x06output\x12=\n" +
	"\fcompleted_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\"f\n" +
	"\x0eGPSCoordinates\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12\x1a\n" +
	"\baltitude\x18\x03 \x01(\x01R\baltitude\"M\n" +
	"\x14ManageSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\"P\n" +
	"\x15ManageSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"\x89\x01\n" +
	"\x0fLogEventRequest\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12\x1d\n" +
	"\n" +
	"event_data\x18\x02 \x01(\fR\teventData\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\\\n" +
	"\x10LogEventResponse\x12\x1f\n" +
	"\vledger_hash\x18\x01 \x01(\tR\n" +
	"ledgerHash\x12'\n" +
	"\x0fsequence_number\x18\x02 \x01(\x03R\x0esequenceNumber2\x90\x02\n" +
	"\fControlPlane\x12[\n" +
	"\x0eExecuteSandbox\x12#.controlplane.ExecuteSandboxRequest\x1a$.controlplane.ExecuteSandboxResponse\x12X\n" +
	"\rManageSession\x12\".controlplane.ManageSessionRequest\x1a#.controlplane.ManageSessionResponse\x12I\n" +
	"\bLogEvent\x12\x1d.controlplane.LogEventRequest\x1a\x1e.controlplane.LogEventResponseB9Z7github.com/Arkhe-Network/UN-v2.0/api/proto;controlplaneb\x06proto3"

var (
	file_api_proto_control_plane_proto_rawDescOnce sync.Once
	file_api_proto_control_plane_proto_rawDescData []byte
)

func file_api_proto_control_plane_proto_rawDescGZIP() []byte {
	file_api_proto_control_plane_proto_rawDescOnce.Do(func() {
		file_api_proto_control_plane_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_control_plane_proto_rawDesc), len(file_api_proto_control_plane_proto_rawDesc)))
	})
	return file_api_proto_control_plane_proto_rawDescData
}

var file_api_proto_control_plane_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_proto_control_plane_proto_goTypes = []any{
	(*ExecuteSandboxRequest)(nil),  // 0: controlplane.ExecuteSandboxRequest
	(*ExecuteSandboxResponse)(nil), // 1: controlplane.ExecuteSandboxResponse
	(*GPSCoordinates)(nil),         // 2: controlplane.GPSCoordinates
	(*ManageSessionRequest)(nil),   // 3: controlplane.ManageSessionRequest
	(*ManageSessionResponse)(nil),  // 4: controlplane.ManageSessionResponse
	(*LogEventRequest)(nil),        // 5: controlplane.LogEventRequest
	(*LogEventResponse)(nil),       // 6: controlplane.LogEventResponse
	(*timestamppb.Timestamp)(nil),  // 7: google.protobuf.Timestamp
}
var file_api_proto_control_plane_proto_depIdxs = []int32{
	2, // 0: controlplane.ExecuteSandboxRequest.location:type_name -> controlplane.GPSCoordinates
	7, // 1: controlplane.ExecuteSandboxResponse.completed_at:type_name -> google.protobuf.Timestamp
	7, // 2: controlplane.LogEventRequest.timestamp:type_name -> google.protobuf.Timestamp
	0, // 3: controlplane.ControlPlane.ExecuteSandbox:input_type -> controlplane.ExecuteSandboxRequest
	3, // 4: controlplane.ControlPlane.ManageSession:input_type -> controlplane.ManageSessionRequest
	5, // 5: controlplane.ControlPlane.LogEvent:input_type -> controlplane.LogEventRequest
	1, // 6: controlplane.ControlPlane.ExecuteSandbox:output_type -> controlplane.ExecuteSandboxResponse
	4, // 7: controlplane.ControlPlane.ManageSession:output_type -> controlplane.ManageSessionResponse
	6, // 8: controlplane.ControlPlane.LogEvent:output_type -> controlplane.LogEventResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_proto_control_plane_proto_init() }
func file_api_proto_control_plane_proto_init() {
	if File_api_proto_control_plane_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_control_plane_proto_rawDesc), len(file_api_proto_control_plane_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_control_plane_proto_goTypes,
		DependencyIndexes: file_api_proto_control_plane_proto_depIdxs,
		MessageInfos:      file_api_proto_control_plane_proto_msgTypes,
	}.Build()
	File_api_proto_control_plane_proto = out.File
	file_api_proto_control_plane_proto_goTypes = nil
	file_api_proto_control_plane_proto_depIdxs = nil
}
